// GOLDEN INTEROP: read a `.kdbx` produced by an INDEPENDENT implementation
// (pykeepass) with dgvault's KdbxCodec. This is the real third-party
// compatibility check the plan flagged as the last Phase-1 KDBX item.
//
// Fixture: test/fixtures/kdbx/reference_aes_argon2.kdbx — KDBX 4, AES-256,
// Argon2d (I=14, M=64MiB, P=2), gzip, ChaCha20 inner random stream.
// Password: 'correct horse battery staple'. Generated by tool described in
// reviews/Performer-round-23.md.
//
// Reading it end-to-end exercises: Argon2d KDF + KeePass composite key, master
// key tree, header SHA-256 + HMAC over the ORIGINAL header bytes, HMAC block
// stream, AES-256-CBC body, gzip, KDBX4 inner header, and the ChaCha20
// inner-random-stream decryption of the protected password.

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:dgvault/core/core.dart';
import 'package:dgvault/core/crypto/impl/argon2_kdf.dart';
import 'package:dgvault/core/crypto/impl/kdbx4_body_cipher.dart';
import 'package:dgvault/data/format/gzip_compressor.dart';
import 'package:test/test.dart';

void main() {
  final file =
      File('test/fixtures/kdbx/reference_aes_argon2.kdbx').readAsBytesSync();
  final cred = CompositeCredential(password: Uint8List.fromList(utf8.encode('correct horse battery staple')));

  KdbxCodec codec() => KdbxCodec(
        bodyCipher: Kdbx4BodyCipher(kdf: const Argon2KeyDerivation()),
        compressor: const GzipCompressor(),
      );

  test('decodes a pykeepass-written KDBX4 (AES/Argon2d/ChaCha20 inner stream)',
      () async {
    final db = await codec().read(file, cred);

    // Walk to the entry (root group -> 'Sub Work' -> entry).
    final entries = _allEntries(db.root).toList();
    final e = entries.firstWhere((e) => e.fields['Title']?.value.reveal() == 'Acme Corp');

    expect(e.fields['UserName']!.value.reveal(), 'alice');
    // The password is Protected="True": decrypted via the ChaCha20 inner stream.
    expect(e.fields['Password']!.value.reveal(), 's3cret!');
    expect(e.fields['Password']!.isProtected, isTrue);
    expect(e.fields['URL']!.value.reveal(), 'https://acme.example');
    expect(e.fields['Notes']!.value.reveal(), 'line1 line2');
  });

  test('wrong password fails the header HMAC', () async {
    expect(
        () => codec().read(file, CompositeCredential(password: Uint8List.fromList(utf8.encode('nope')))),
        throwsA(isA<KdbxIntegrityException>()),);
  });
}

Iterable<Entry> _allEntries(Group g) sync* {
  yield* g.entries;
  for (final c in g.groups) {
    yield* _allEntries(c);
  }
}
